jobs:
  lint:
    commands:
      - flake8
      - pydocstyle
      - mypy .

  clean:
    script: clean_build_dirs.py
    option_arguments:
      --project-dir: .
      --target-dirs: build dist templ8.egg-info docs/api

  format:
    commands:
      - isort --apply -sl
      - >-
        autoflake . -ri --exclude "venv, conftest.py"
        --remove-all-unused-imports --remove-unused-variables
        --ignore-init-module-imports
      - isort --apply
      - black .

  docs:
    command: sphinx-build docs/ build/

  tests:
    command: pytest --cov yummy_cereal --html .test_report.html --self-contained-html

  prototype-unit-tests:
    command: python3 -m PyTestStub.GenerateUnitTests .
  
  prototype-bdd-tests:
    script: prototype-bdd-tests.py
    positional_arguments:
      - tests/behaviour_tests

  missing-docstrings:
    command: find multi_job -type f -name "*.py" | xargs pylint --disable=all --enable=C0114,C0115,C0116
  
  release:
    commands:
      - bump2version <release_type>
      - python3 setup.py sdist bdist_wheel
      - twine upload dist/* --username <twine_username>
    context:
      release_type: patch
      twine_username: joellefkowitz

routines:
  pre-commit:
    - clean
    - lint
    - format

  pre-release:
    - prototype-bdd-tests
    - prototype-unit-tests
    - missing-docstrings

meta:
  project_root: ../
  scripts_root: ../scripts/
