package: True

name: multi-job
version: 0.10.15
description: Job runner for multifaceted projects

author: Joel Lefkowitz
author_email: joellefkowitz@hotmail.com
author_github: JoelLefkowitz

private: False
package_name: multi_job

buildbot_worker_password: "Is this a pigeon?"
buildbot_database_password: "Is this a pigeon?"

keywords: [job, runner]
twine_username: joellefkowitz
python_version: 3.6

console_scripts: []
install_requires: []
