
jobs:
  fmt:
    function: dev_actions/fmt:main
    targets:
      - app
      - server

  lint:
    command: "pylint ."
    targets: all
  
  bump:
    command: "bumpversion <bump-type>"
    skips: app
    context:
      bump-type: patch

  boot:
    script: ../boot.bash

  clean:
    function: prod_actions/clean:main
    context:
      clean_dirs:
        - build
        - dist
        - multi_job.egg-info

  pypi-upload:
    function: prod_actions/pypi_upload:main
    context:
      release_type: patch
      twine_username: joellefkowitz

projects:
  app:
    path: ../app
  
  server:
    path: ../server
    context:
      bump-type: minor
  
  models:
    path: ../models
  
routines:
  dev:
    - fmt
    - lint

