jobs:
  fmt:
    function: fmt:main
    targets:
      - multi_job

  clean:
    function: clean:main
    context:
      clean_dirs:
        - build
        - dist
        - multi_job.egg-info

  pypi-upload:
    function: pypi_upload:main
    context:
      release_type: patch
      twine_username: joellefkowitz

projects:
  projects:
    multi_job:
      path: ../multi_job
