jobs:
  fmt:
    command: black . --exclude venv
    targets:
      - all

  yenv:
    function: yenv:main
    context:
      yenv-file: ../environment.yml
      env-targets:
        - multi-job

  clean:
    function: clean:main
    context:
      clean_dirs:
        - build
        - dist
        - multi-job.egg-info

  pypi-upload:
    function: pypi_upload:main
    context:
      release_type: patch
      twine_username: joellefkowitz


projects:
  multi-job:
    path: ../multi-job

routines:
  release:
    - fmt
    - clean
    - pypi_upload
